### ISSUE TITLE
how to use join in elasticsearcch?

### ISSUE THREAD

**Issue by prashantgupta27** [satendrakumar/es-java-client-sample#3]

**Comment by prashantgupta27** [comment]
how to use join in elastic search? and  how design schema  for e-site

**Comment by satendrakumar** [comment]
@prashantgupta27 There is no concept of join in elasticsearch. you can use nested [query](https://discuss.elastic.co/) for join. This is right place https://discuss.elastic.co/ to ask question

**Comment by prashantgupta27** [comment]
OK Thanks for  suggestion
